In [1]:
import numpy as np

In [7]:
arr = np.linspace(0, 10, 11)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
arr = np.linspace(0, 10, 11, dtype = int)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.arange(0, 5, 0.5)
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# Find element

In [3]:
arr = np.linspace(0, 10, 11)
np.where(arr==3)

(array([], dtype=int64),)